name: dotnet build

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

jobs:
  build:
    defaults:
      run:
        working-directory: demo/GraphTutorial
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
